version: "3"
services:
  postgres:
    image: postgres:11.4
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demotests

volumes:
  postgresql: