# Generated by Django 2.2.4 on 2019-10-16 21:32

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=150, unique=True)),
                (
                    'slug',
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        overwrite=True,
                        populate_from='name',
                    ),
                ),
                ('tag', models.CharField(max_length=100)),
                ('url', models.URLField()),
                (
                    'content_type',
                    models.CharField(
                        choices=[
                            ('cp', 'Cupom'),
                            ('cb', 'Combo'),
                            ('cm', 'Communication'),
                        ],
                        default='cb',
                        max_length=2,
                    ),
                ),
                (
                    'gender',
                    models.CharField(
                        choices=[('m', 'Male'), ('f', 'Female')],
                        default='f',
                        max_length=1,
                    ),
                ),
                (
                    'goal',
                    models.CharField(
                        choices=[
                            ('awar', 'Awareness'),
                            ('cons', 'Consideration'),
                            ('conv', 'Conversion'),
                        ],
                        default='awar',
                        max_length=4,
                    ),
                ),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        )
    ]
